services:
  app:
    platform: linux/amd64
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 9527:9527
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run dev
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    environment:
      NODE_ENV: development
      DB_URI: mongodb://mongodb:27017/shorturl_db
    depends_on:
      - mongodb
  mongodb:
    platform: linux/amd64
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db